name: opendataswiss
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - jupyter
  - ipykernel
  - pip
  - pip:
    - missingno
    - scikit-learn
